[package]
name = "a2o4-server"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.86"
directories = "6.0.0"
enum-iterator = "2.1.0"
regex = "1.11.1"
reqwest = { version = "0.12.5", features = ["blocking", "cookies"] }
rocket = { version = "0.5.1", features = ["json"] }
scraper = "0.22.0"
serde = { version = "1.0.210", features = ["derive"] }
ssh2 = "0.9.4"
strum = "0.26.3"
strum_macros = "0.26.4"
tokio = { version = "1.41.1", features = ["fs"] }
toml = "0.8.19"
url = "2.5.2"
