[package]
name = "a2o4-server"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.86"
cookie_store = "0.22.1"
derive_builder = "0.20.2"
directories = "6.0.0"
enum_dispatch = "0.3.13"
enum-iterator = "2.1.0"
epub = "2.1.4"
indexmap = "2.2.6"
regex = "1.11.1"
reqwest = { version = "0.13.3", features = ["blocking", "cookies", "form", "multipart", "stream"] }
reqwest_cookie_store = { version = "0.10.0", features = ["serde"] }
reqwest-websocket = "0.6.0"
rocket = { version = "0.5.1", features = ["json"] }
scraper = { version = "0.22.0", features = ["atomic"] }
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.120"
ssh2 = "0.9.4"
strum = "0.26.3"
strum_macros = "0.26.4"
tokio = { version = "1.41.1", features = ["fs"] }
toml = "0.8.19"
url = "2.5.2"
